name: Continous integration
on: [push]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install
        shell: bash
        run: |
          sudo apt-get install xvfb python3-tk python3-dev
          pip3 install -e .

      - name: Lint
        shell: bash
        run: |
          pip3 install isort black autoflake
          make lint

      - name: Test
        shell: bash
        run: xvfb-run -a -s "-screen 0 640x480x8" sleepness --help
